on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master

name: Continuous Integration

jobs:
  releaseMasterBranchOnly:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3
    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # tag: v3
      with:
        node-version: '16.x'
    - name: Install dependencies
      run: yarn install --frozen-lockfile
    - name: Run tests
      run: yarn test
    - name: Publish via semantic-release
      if: github['ref'] == 'refs/heads/master'
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
        NPM_TOKEN: ${{ secrets.NPM_AUTH_TOKEN }}
      run: yarn run semantic-release
