on:
  schedule:
    - cron: '0 9 * * *'

name: Update API History Data

jobs:
  updateHistoryFiles:
    name: Update history files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@ac593985615ec2ede58e132d2e21d2b1cbd6127c  # tag: v3
    - uses: actions/setup-node@64ed1c7eab4cce3362f8c340dee64e5eaeef8f7c  # tag: v3
      with:
        node-version: '16.x'
    - name: Update history files
      run: yarn run update
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
