on:
  schedule:
    - cron: '0 9 * * *'

name: Update API History Data

jobs:
  updateHistoryFiles:
    name: Update history files
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2.3.4
    - uses: actions/setup-node@v2.2.0
      with:
        node-version: '12.x'
    - name: Update history files
      run: npm run update
      env:
        GH_TOKEN: ${{ secrets.GH_TOKEN }}
